version: 2
sphinx:
    configuration: doc/conf.py
    builder: html
    fail_on_warning: false

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  #tools:
  #  python: "3.11"

conda:
    environment: environment_rtd.yml

formats: []
