# This Snakefile read all Fastq files in the current directory
# and convert them into Fasta
#
# How to run ? If you have 8 cores:
#
#     snakemake -s Snakefile --cores 8
#
# on a SLURM framework, :
#
#     snakemake -s Snakefile --cluster "-j 8 --mem 4000"
import glob

in_ext = "fastq.gz"
out_ext = "fasta"
command = "fastq2fasta"

# nothing to change below
#
samples = glob.glob(f"*.{in_ext}")
samples = [x.rsplit(".")[0] for x in samples]

rule all:
    input: expand(f"{{dataset}}.{out_ext}", dataset=samples)

rule bioconvert:
    input: f"{{dataset}}.{in_ext}"
    output: f"{{dataset}}.{out_ext}"
    run:
        cmd = f"bioconvert {command} "
        cmd += " {input} {output}"
        shell(cmd)

