name: Trigger All Workflows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core:
    uses: ./.github/workflows/core.yml
  main:
    uses: ./.github/workflows/main.yml
  batch1:
    uses: ./.github/workflows/all_batch1.yml
  batch2:
    uses: ./.github/workflows/all_batch2.yml
  batch3:
    uses: ./.github/workflows/all_batch3.yml
